workspace_root: ${ORBIT_WS}

world:
  base_scene: usd_files/earth/earthmodel.usd

simulation:
  mu: 398600.4418      # km³/s²
  dt_sim: 0.00833      # ~1/120 s

bodies:

  - name: earth
    prim_path: /World/Earth
    role: attractor
    spawn: false

  - name: sat1
    prim_path: /World/Sat1
    role: orbit
    spawn: true
    usd: urdf/bigsat/bigsat.usd
    attractor: /World/Earth
    orbit:
      type: circular
      radius: 6778000   
      plane: xy
    scale: 1.0       

  - name: sat2
    prim_path: /World/Sat2
    role: orbit
    spawn: true
    usd: urdf/smallsat/smallsat.usd
    attractor: /World/Earth
    orbit:
      type: elements
      a: 6778000
      e: 0.01
      inc: 28.5
      raan: 0.0
      argp: 0.0
      nu: 45.0
    scale: 1.0

  - name: sat3
    prim_path: /World/Sat3
    role: cw
    spawn: true
    usd: urdf/smallsat/smallsat.usd
    attractor: /World/Earth
    chief: /World/Sat1
    orbit:
      type: cw_relative
      dr: [1.0, 0.0, 0.5]
      dv: [0.0, 0.001, 0.0]
    scale: 1.0